export interface RevenueOverviewDataType {
    id: number
    orderNo : string
    image: string
    name: string
    email : string
    description : string
    amount : string
    date : string
}

export const RevenueOverviewData : RevenueOverviewDataType[] = [
    {
        id: 1,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 2,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 3,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 4,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 5,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 6,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 7,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 8,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 9,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 10,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 95,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
    {
        id: 105,
        orderNo : "ORD-001",
        image: "/assets/img/booking_user.png",
        name: "Sarah James",
        email : "Sarah@gmail.com",
        description : "Consultation Session",
        amount : "$150.00",
        date : "Jan 6, 2025",
    },
];